# G231210355 Metehan Gülşer
# B231210355 Emir Kır
# G231210387 Yiğit Alp Çakır
# B211210006 Muhammet Enes Nas
# B221210003 Akif Emre Yaman


CC = gcc
CFLAGS = -Wall -Wextra -std=c99

# Hedef dosya adı
TARGET = shell

# Kaynak dosyalar
SRCS = main.c
HDRS = main.h

# Derleme sonucu oluşacak dosya
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean